prometheus:
  serverFiles:
    prometheus.yml:
      scrape_configs: []
  rbac:
    create: false
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  pushgateway:
    enabled: false
  server:
    extraFlags:
      - web.enable-lifecycle
      - web.enable-remote-write-receiver
      - enable-feature=exemplar-storage
    deploymentAnnotations:
      odigos.io/skip: "true"
tempo:
  annotations: 
    odigos.io/skip: "true"
  config: |
    metrics_generator_enabled: true
    search_enabled: true
    multitenancy_enabled: {{ .Values.tempo.multitenancyEnabled }}
    compactor:
      compaction:
        compacted_block_retention: {{ .Values.tempo.retention }}
    distributor:
      receivers:
        {{- toYaml .Values.tempo.receivers | nindent 8 }}
    ingester:
      {{- toYaml .Values.tempo.ingester | nindent 6 }}
    server:
      {{- toYaml .Values.tempo.server | nindent 6 }}
    storage:
      {{- toYaml .Values.tempo.storage | nindent 6 }}
    overrides:
      per_tenant_override_config: /conf/overrides.yaml
      metrics_generator_processors:
        - service-graphs
        - span-metrics
    metrics_generator:
      storage:
        path: /var/tempo/wal
        remote_write:
          - url: http://observability-prometheus-server.observability/api/v1/write
            send_exemplars: true
loki:
  rbac:
    pspEnabled: false
  annotations:
    odigos.io/skip: "true"
grafana:
  rbac:
    pspEnabled: false
  annotations:
    odigos.io/skip: "true"
  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    feature_toggles:
      enable: tempoSearch, tempoBackendSearch
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        uid: Prometheus
        url: http://observability-prometheus-server.observability
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - datasourceUid: Tempo
              name: traceID
      - name: Loki
        type: loki
        uid: Loki
        access: proxy
        url: "http://observability-loki.observability:3100"
        correlations:
        - targetUID: Tempo
          label: "Tempo traces"
          description: "Related traces stored in Tempo"
        jsonData:
          derivedFields:
            - name: "traceID"
              matcherRegex: "trace_id=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: Tempo
      - name: Tempo
        type: tempo
        uid: Tempo
        access: proxy
        url: "http://observability-tempo.observability:3100"
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'Loki'
            tags: ['k8s.pod.name']
            mappedTags: [{ key: 'k8s.pod.name', value: 'k8s_pod_name' }]
            mapTagNamesEnabled: true
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: 'Prometheus'
          search:
            hide: false
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: 'Loki'
